# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-31 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=20, verbose_name='收件人')),
                ('aphone', models.CharField(max_length=11, null=True, verbose_name='收件电话')),
                ('address', models.CharField(max_length=50, null=True, verbose_name='收件地址')),
            ],
            options={
                'db_table': 'address',
                'verbose_name_plural': '收件地址',
                'verbose_name': '收件地址',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=20, verbose_name='车名')),
                ('carprice', models.FloatField(null=True, verbose_name='价格')),
            ],
            options={
                'db_table': 'car',
                'verbose_name_plural': '车',
                'verbose_name': '车',
            },
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbrand', models.CharField(max_length=20, verbose_name='车的品牌')),
            ],
            options={
                'db_table': 'carbrand',
                'verbose_name_plural': '车的品牌',
                'verbose_name': '车的品牌',
            },
        ),
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carcolor', models.CharField(max_length=20, verbose_name='车的颜色')),
            ],
            options={
                'db_table': 'carcolor',
                'verbose_name_plural': '车的颜色',
                'verbose_name': '车的颜色',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ManyToManyField(null=True, to='car.Car', verbose_name='车')),
            ],
            options={
                'db_table': 'cart',
                'verbose_name_plural': '购物车',
                'verbose_name': '购物车',
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartype', models.CharField(max_length=20, verbose_name='车的类型')),
            ],
            options={
                'db_table': 'cartype',
                'verbose_name_plural': '车的类型',
                'verbose_name': '车的类型',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300, verbose_name='评价')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.Car', verbose_name='车的信息')),
            ],
            options={
                'db_table': 'comment',
                'verbose_name_plural': '评论',
                'verbose_name': '评论',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/upload/car', verbose_name='图片')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Car', verbose_name='车的信息')),
            ],
            options={
                'db_table': 'image',
                'verbose_name_plural': '图片',
                'verbose_name': '图片',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.Address', verbose_name='收件地址')),
                ('car', models.ManyToManyField(null=True, to='car.Car', verbose_name='车')),
            ],
            options={
                'db_table': 'order',
                'verbose_name_plural': '订单',
                'verbose_name': '订单',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uphone', models.CharField(max_length=11, null=True, verbose_name='用户电话')),
                ('uname', models.CharField(max_length=20, verbose_name='用户姓名')),
                ('upassword', models.CharField(max_length=20, verbose_name='用户密码')),
                ('isActive', models.BooleanField(default='True', verbose_name='是否启用')),
            ],
            options={
                'db_table': 'user',
                'verbose_name_plural': '用户信息',
                'verbose_name': '用户信息',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.User', verbose_name='用户信息'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='car',
            name='carbrand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.CarBrand', verbose_name='车的品牌'),
        ),
        migrations.AddField(
            model_name='car',
            name='carcolor',
            field=models.ManyToManyField(null=True, to='car.CarColor', verbose_name='车的颜色'),
        ),
        migrations.AddField(
            model_name='car',
            name='cartype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.CarType', verbose_name='车的类型'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.User', verbose_name='买家信息'),
        ),
    ]
