# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='carname',
            field=models.CharField(max_length=20, null=True, verbose_name='车名'),
        ),
        migrations.AlterField(
            model_name='car',
            name='carcolor',
            field=models.ManyToManyField(to='car.CarColor', verbose_name='车的颜色'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='car',
            field=models.ManyToManyField(to='car.Car', verbose_name='车'),
        ),
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ManyToManyField(to='car.Car', verbose_name='车'),
        ),
    ]
