# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20180205_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carimage',
            field=models.ImageField(null=True, upload_to='static/upload/car/title', verbose_name='图片'),
        ),
    ]
