# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_car_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='carname',
            field=models.CharField(max_length=20, null=True, verbose_name='车名'),
        ),
        migrations.AddField(
            model_name='cart',
            name='carprice',
            field=models.FloatField(null=True, verbose_name='单价'),
        ),
        migrations.AddField(
            model_name='cart',
            name='count',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='cart',
            name='uname',
            field=models.CharField(max_length=20, null=True, verbose_name='用户名'),
        ),
    ]
