# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20180205_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='createdat',
            field=models.DateField(null=True, verbose_name='加入购物车时间'),
        ),
    ]
