# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_cart_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='count',
            new_name='carcount',
        ),
    ]
