# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_auto_20180206_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='createdat',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='加入购物车时间'),
        ),
    ]
