# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_auto_20180207_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='uname',
        ),
    ]
