# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_remove_order_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Address', verbose_name='收件地址'),
        ),
    ]
