# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_order_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uaddress',
            field=models.CharField(max_length=20, null=True, verbose_name='收货地址'),
        ),
    ]
