# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0015_order_carprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='createdat',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='订单创建时间'),
        ),
    ]
