# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0016_order_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='uname',
        ),
        migrations.AddField(
            model_name='order',
            name='carcount',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='order',
            name='carimage',
            field=models.ImageField(null=True, upload_to='static/upload/car/order', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='order',
            name='carname',
            field=models.CharField(max_length=20, null=True, verbose_name='车名'),
        ),
    ]
