# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0018_auto_20180207_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='uname',
            field=models.CharField(max_length=20, null=True, verbose_name='用户名'),
        ),
    ]
