# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0019_comment_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='carimage',
            field=models.ImageField(null=True, upload_to='static/upload/car/cart', verbose_name='图片'),
        ),
    ]
