# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0020_cart_carimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='car',
        ),
    ]
